### ISSUE TITLE
#US06 #TK18 Revisar  el Responsive del sitio web y corregir las paginas que sean necesarias

### ISSUE THREAD

**Issue by wils09** [TSDWAD2023com1grupo1/DressCodeGroup#52]

**Comment by noahcassutti** [comment]
Se dividieron las paginas entre integrantes del equipo y cada uno creo un componente en angular y se corrigieron

**Comment by noahcassutti** [comment]
Se dividió lo siguiente:

-Navbar: Elena Ponce (dejo la carrera)
-Footer: Maria Belen Colado
-Productos: Noah Cassutti
-Quienes somos: Elizabeth Chialva
-Contacto: Cris Coradini
-Dashboard: Javier Carranza
-Login y registro: Santiago Bertorello
-Landing: Todos (lo realizamos por Meet y la subió un solo integrante)

**Comment by SantiagoBertorello** [comment]
- [x]  -Navbar: Elena Ponce (dejo la carrera)

- [x]  -Footer: Maria Belen Colado

- [x]  -Productos: Noah Cassutti

- [x] -Quienes somos: Elizabeth Chialva ( lo realizo Noah Cassuti)

- [x]  -Contacto: Cris Coradini

- [x]  -Dashboard: Javier Carranza

- [x]  -Login y registro: Santiago Bertorello

- [x]  -Landing: Todos (lo realizamos por Meet y la subió un solo integrante)
